# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ExcelBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ExcelBox.setGeometry(QtCore.QRect(40, 270, 121, 26))
        self.ExcelBox.setObjectName("ExcelBox")
        self.PDFBox = QtWidgets.QCheckBox(self.centralwidget)
        self.PDFBox.setGeometry(QtCore.QRect(40, 300, 101, 26))
        self.PDFBox.setObjectName("PDFBox")
        self.RemoveButton = QtWidgets.QRadioButton(self.centralwidget)
        self.RemoveButton.setGeometry(QtCore.QRect(40, 190, 301, 21))
        self.RemoveButton.setObjectName("RemoveButton")
        self.CopyButton = QtWidgets.QRadioButton(self.centralwidget)
        self.CopyButton.setGeometry(QtCore.QRect(40, 220, 112, 26))
        self.CopyButton.setObjectName("CopyButton")
        self.IndexButton = QtWidgets.QRadioButton(self.centralwidget)
        self.IndexButton.setGeometry(QtCore.QRect(40, 150, 131, 26))
        self.IndexButton.setObjectName("IndexButton")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(350, 150, 461, 311))
        self.treeWidget.setObjectName("treeWidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(30, 380, 171, 71))
        self.StartButton.setObjectName("StartButton")
        self.PathBox = QtWidgets.QTextEdit(self.centralwidget)
        self.PathBox.setGeometry(QtCore.QRect(40, 90, 771, 41))
        self.PathBox.setObjectName("PathBox")
        self.SingleBillBox = QtWidgets.QCheckBox(self.centralwidget)
        self.SingleBillBox.setGeometry(QtCore.QRect(40, 40, 161, 26))
        self.SingleBillBox.setObjectName("SingleBillBox")
        self.LogoBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.LogoBox.setGeometry(QtCore.QRect(690, 10, 121, 71))
        self.LogoBox.setObjectName("LogoBox")
        self.PrintBox = QtWidgets.QCheckBox(self.centralwidget)
        self.PrintBox.setGeometry(QtCore.QRect(220, 400, 61, 26))
        self.PrintBox.setObjectName("PrintBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 25))
        self.menubar.setObjectName("menubar")
        self.menuMAS_Reader = QtWidgets.QMenu(self.menubar)
        self.menuMAS_Reader.setObjectName("menuMAS_Reader")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDatei = QtWidgets.QAction(MainWindow)
        self.actionDatei.setObjectName("actionDatei")
        self.menuMAS_Reader.addAction(self.actionDatei)
        self.menubar.addAction(self.menuMAS_Reader.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExcelBox.setText(_translate("MainWindow", "Excel Export"))
        self.PDFBox.setText(_translate("MainWindow", "PDF Export"))
        self.RemoveButton.setText(_translate("MainWindow", "Verschieben (Doppelte Überschreiben)"))
        self.CopyButton.setText(_translate("MainWindow", "Kopieren"))
        self.IndexButton.setText(_translate("MainWindow", "Nur Indizieren"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Aufstellorte"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Rechnungen"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.PathBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Input</span></p></body></html>"))
        self.SingleBillBox.setText(_translate("MainWindow", "Einzelne Rechnung"))
        self.PrintBox.setText(_translate("MainWindow", "Print"))
        self.menuMAS_Reader.setTitle(_translate("MainWindow", "MAS Reader"))
        self.actionDatei.setText(_translate("MainWindow", "Datei"))
